/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint confirming API service and database connectivity.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint confirming API service and database connectivity.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List and search destinations
         * @description Retrieve all available travel destinations or filter by search query.
         */
        get: operations["list_destinations_api_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{destination_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get destination details
         * @description Retrieve comprehensive destination reference data including attractions, hotels, restaurants, and transport connections.
         */
        get: operations["get_destination_api_destinations__destination_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a trip (single-city or multi-city)
         * @description Generate a fully scheduled, budgeted, and route-optimized single-city or multi-city itinerary.
         */
        post: operations["plan_trip_api_trips_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trip details
         * @description Retrieve the complete active trip state including metadata, stops, transport legs, accommodation, day-by-day itinerary, budget breakdown, and schedule validation status.
         */
        get: operations["get_trip_api_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent interactive chat & modification
         * @description Conversational interface powered by Gemini orchestrator with safe tool calling. Dispatches deterministic engine operations without exposing chain-of-thought.
         */
        post: operations["chat_with_agent_api_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/events/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get structured agent events
         * @description Retrieve structured execution audit trail for a trip. Excludes internal chain-of-thought.
         */
        get: operations["get_agent_events_api_agent_events__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disruptions/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger disruption analysis and replanning
         * @description Analyze a disruption event, score candidate alternatives, and return a candidate replan proposal in an isolated branch without mutating active trip state.
         */
        post: operations["trigger_disruption_api_disruptions_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disruptions/{replan_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply proposed replan to active trip
         * @description Mutating operation: commits a verified proposed replan to the active trip state if not stale.
         */
        post: operations["apply_replan_api_disruptions__replan_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disruptions/{replan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject proposed replan
         * @description Discards a proposed replan. Active trip state remains completely untouched.
         */
        post: operations["reject_replan_api_disruptions__replan_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run what-if simulation
         * @description Simulates hypothetical changes (budget change, add day, remove/replace destination, add activity) in an isolated branch without mutating active trip state.
         */
        post: operations["run_what_if_simulation_api_simulations_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{simulation_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply simulation branch to active trip
         * @description Mutating operation: commits a verified simulation branch to the active trip state if not stale and feasible.
         */
        post: operations["apply_simulation_api_simulations__simulation_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{simulation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject simulation branch
         * @description Discards a simulation branch. Active trip state remains completely untouched.
         */
        post: operations["reject_simulation_api_simulations__simulation_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentChatRequest */
        AgentChatRequest: {
            /** Trip Id */
            trip_id: string;
            /** Message */
            message: string;
        };
        /** AgentChatResponse */
        AgentChatResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            /** Reply */
            reply: string;
            /** Updated Trip */
            updated_trip?: {
                [key: string]: unknown;
            } | null;
            /** Executed Tools */
            executed_tools?: string[];
        };
        /** AgentEventItem */
        AgentEventItem: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Tool Name */
            tool_name?: string | null;
            /** Input Summary */
            input_summary?: string | null;
            /** Result Summary */
            result_summary?: string | null;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number;
            /** Created At */
            created_at: string;
        };
        /** AgentEventsResponse */
        AgentEventsResponse: {
            /** Trip Id */
            trip_id: string;
            /** Events */
            events: components["schemas"]["AgentEventItem"][];
            /** Count */
            count: number;
        };
        /** ApplyReplanResponse */
        ApplyReplanResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            /**
             * Message
             * @default Disruption replan applied successfully.
             */
            message: string;
            /** Applied Items Count */
            applied_items_count: number;
            /** Applied Legs Count */
            applied_legs_count: number;
            diff: components["schemas"]["PlanDiffResult"];
        };
        /** ApplySimulationResponse */
        ApplySimulationResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /**
             * Message
             * @default Simulation branch applied to active trip.
             */
            message: string;
            /** Items Count */
            items_count: number;
        };
        /** BudgetCalculationResult */
        BudgetCalculationResult: {
            /**
             * Accommodation
             * @default 0
             */
            accommodation: number;
            /**
             * Intercity Transport
             * @default 0
             */
            intercity_transport: number;
            /**
             * Local Transport
             * @default 0
             */
            local_transport: number;
            /**
             * Activities
             * @default 0
             */
            activities: number;
            /**
             * Food
             * @default 0
             */
            food: number;
            /**
             * Miscellaneous
             * @default 0
             */
            miscellaneous: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Budget
             * @default 0
             */
            budget: number;
            /**
             * Remaining
             * @default 0
             */
            remaining: number;
            /**
             * Variance
             * @default 0
             */
            variance: number;
            /**
             * Percentage Used
             * @default 0
             */
            percentage_used: number;
            /**
             * Within Budget
             * @default true
             */
            within_budget: boolean;
            /**
             * Traveler Count
             * @default 1
             */
            traveler_count: number;
            /**
             * Cost Per Traveler
             * @default 0
             */
            cost_per_traveler: number;
            /** Daily Breakdowns */
            daily_breakdowns?: components["schemas"]["DailyBudgetBreakdown"][];
        };
        /** CandidateAlternative */
        CandidateAlternative: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Rating */
            rating: number;
            /** Entry Fee */
            entry_fee: number;
            /**
             * Distance Km
             * @default 0
             */
            distance_km: number;
            /**
             * Travel Time From Prev Mins
             * @default 0
             */
            travel_time_from_prev_mins: number;
            /**
             * Travel Time To Next Mins
             * @default 0
             */
            travel_time_to_next_mins: number;
            /** Open Time */
            open_time: string;
            /** Close Time */
            close_time: string;
            /**
             * Is Feasible
             * @default true
             */
            is_feasible: boolean;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Score Breakdown */
            score_breakdown?: {
                [key: string]: number;
            };
        };
        /**
         * CoreDisruptionType
         * @enum {string}
         */
        CoreDisruptionType: "VENUE_CLOSED" | "TRANSPORT_DELAY" | "TRANSPORT_CANCELLED" | "WEATHER_ALERT" | "BOOKING_UNAVAILABLE" | "BUDGET_REDUCTION" | "SCHEDULE_CONFLICT";
        /** DailyBudgetBreakdown */
        DailyBudgetBreakdown: {
            /** Day Number */
            day_number: number;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Destination Name */
            destination_name: string;
            /**
             * Accommodation Cost
             * @default 0
             */
            accommodation_cost: number;
            /**
             * Intercity Transport Cost
             * @default 0
             */
            intercity_transport_cost: number;
            /**
             * Local Transport Cost
             * @default 0
             */
            local_transport_cost: number;
            /**
             * Activities Cost
             * @default 0
             */
            activities_cost: number;
            /**
             * Food Cost
             * @default 0
             */
            food_cost: number;
            /**
             * Miscellaneous Cost
             * @default 0
             */
            miscellaneous_cost: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
        };
        /** DestinationDetailResponse */
        DestinationDetailResponse: {
            destination: components["schemas"]["DestinationSummaryResponse"];
            /** Places */
            places?: components["schemas"]["PlaceResponse"][];
            /** Hotels */
            hotels?: components["schemas"]["HotelResponse"][];
            /** Restaurants */
            restaurants?: components["schemas"]["RestaurantResponse"][];
            /** Transport Connections */
            transport_connections?: components["schemas"]["TransportConnectionResponse"][];
        };
        /** DestinationListResponse */
        DestinationListResponse: {
            /** Items */
            items: components["schemas"]["DestinationSummaryResponse"][];
            /** Count */
            count: number;
        };
        /** DestinationSummaryResponse */
        DestinationSummaryResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State Province */
            state_province?: string | null;
            /**
             * Country
             * @default India
             */
            country: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Ideal Duration Days
             * @default 3
             */
            ideal_duration_days: number;
            /**
             * Average Daily Cost
             * @default 3000
             */
            average_daily_cost: number;
            /** Hero Image Url */
            hero_image_url?: string | null;
            /** Description */
            description?: string | null;
        };
        /** DisruptionAnalysisResult */
        DisruptionAnalysisResult: {
            /** Disruption Id */
            disruption_id: string;
            /** Trip Id */
            trip_id: string;
            type: components["schemas"]["CoreDisruptionType"];
            /** Affected Items */
            affected_items?: {
                [key: string]: unknown;
            }[];
            /** Affected Legs */
            affected_legs?: {
                [key: string]: unknown;
            }[];
            /** Downstream Affected Items */
            downstream_affected_items?: {
                [key: string]: unknown;
            }[];
            /** Available Windows */
            available_windows?: {
                [key: string]: unknown;
            }[];
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /**
             * Required Replan
             * @default true
             */
            required_replan: boolean;
            /** Reasons */
            reasons?: string[];
        };
        /** FieldChange */
        FieldChange: {
            /** Before */
            before: unknown;
            /** After */
            after: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotelResponse */
        HotelResponse: {
            /** Id */
            id: string;
            /** Destination Id */
            destination_id: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Price Per Night */
            price_per_night: number;
            /**
             * Rating
             * @default 4
             */
            rating: number;
            /** Amenities */
            amenities?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Address */
            address?: string | null;
        };
        /** ItemModification */
        ItemModification: {
            /** Item Id */
            item_id: string;
            /** Title */
            title?: string | null;
            /** Field Changes */
            field_changes: {
                [key: string]: components["schemas"]["FieldChange"];
            };
        };
        /** ItineraryItemDetail */
        ItineraryItemDetail: {
            /** Id */
            id: string;
            /** Trip Stop Id */
            trip_stop_id: string;
            /** Item Type */
            item_type: string;
            /** Place Id */
            place_id?: string | null;
            /** Custom Title */
            custom_title?: string | null;
            /** Day Number */
            day_number: number;
            /** Scheduled Date */
            scheduled_date: string;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Cost */
            cost: number;
            /** Status */
            status: string;
            /** Notes */
            notes?: string | null;
            /**
             * Travel Time From Prev Minutes
             * @default 0
             */
            travel_time_from_prev_minutes: number;
            /**
             * Travel Distance Km
             * @default 0
             */
            travel_distance_km: number;
        };
        /** LegModification */
        LegModification: {
            /** Leg Id */
            leg_id: string;
            /** Field Changes */
            field_changes: {
                [key: string]: components["schemas"]["FieldChange"];
            };
        };
        /** PlaceResponse */
        PlaceResponse: {
            /** Id */
            id: string;
            /** Destination Id */
            destination_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Description */
            description?: string | null;
            /**
             * Entry Fee
             * @default 0
             */
            entry_fee: number;
            /**
             * Typical Duration Minutes
             * @default 60
             */
            typical_duration_minutes: number;
            /**
             * Rating
             * @default 4
             */
            rating: number;
            /**
             * Open Time
             * @default 09:00
             */
            open_time: string;
            /**
             * Close Time
             * @default 18:00
             */
            close_time: string;
            /** Closed Days */
            closed_days?: number[];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Image Url */
            image_url?: string | null;
        };
        /** PlanDiffResult */
        PlanDiffResult: {
            /** Added Items */
            added_items?: {
                [key: string]: unknown;
            }[];
            /** Removed Items */
            removed_items?: {
                [key: string]: unknown;
            }[];
            /** Modified Items */
            modified_items?: components["schemas"]["ItemModification"][];
            /** Unchanged Items */
            unchanged_items?: {
                [key: string]: unknown;
            }[];
            /** Added Legs */
            added_legs?: {
                [key: string]: unknown;
            }[];
            /** Removed Legs */
            removed_legs?: {
                [key: string]: unknown;
            }[];
            /** Modified Legs */
            modified_legs?: components["schemas"]["LegModification"][];
            /**
             * Budget Before
             * @default 0
             */
            budget_before: number;
            /**
             * Budget After
             * @default 0
             */
            budget_after: number;
            /**
             * Budget Delta
             * @default 0
             */
            budget_delta: number;
            /**
             * Travel Distance Delta Km
             * @default 0
             */
            travel_distance_delta_km: number;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** ProposedReplan */
        ProposedReplan: {
            /** Replan Id */
            replan_id?: string;
            /** Trip Id */
            trip_id: string;
            disruption_type: components["schemas"]["CoreDisruptionType"];
            /**
             * Feasible
             * @default true
             */
            feasible: boolean;
            /** Proposed Items */
            proposed_items?: {
                [key: string]: unknown;
            }[];
            /** Proposed Stops */
            proposed_stops?: {
                [key: string]: unknown;
            }[];
            /** Proposed Legs */
            proposed_legs?: {
                [key: string]: unknown;
            }[];
            diff: components["schemas"]["PlanDiffResult"];
            budget_before: components["schemas"]["BudgetCalculationResult"];
            budget_after: components["schemas"]["BudgetCalculationResult"];
            validation_before: components["schemas"]["ScheduleValidationResult"];
            validation_after: components["schemas"]["ScheduleValidationResult"];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Candidates Evaluated */
            candidates_evaluated?: components["schemas"]["CandidateAlternative"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** RejectReplanResponse */
        RejectReplanResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            /**
             * Message
             * @default Proposed replan discarded. Active trip unchanged.
             */
            message: string;
        };
        /** RejectSimulationResponse */
        RejectSimulationResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /**
             * Message
             * @default Simulation branch discarded. Active trip unchanged.
             */
            message: string;
        };
        /** RestaurantResponse */
        RestaurantResponse: {
            /** Id */
            id: string;
            /** Destination Id */
            destination_id: string;
            /** Name */
            name: string;
            /** Cuisine */
            cuisine: string;
            /** Price Level */
            price_level?: string | null;
            /**
             * Average Cost Per Person
             * @default 350
             */
            average_cost_per_person: number;
            /**
             * Open Time
             * @default 11:00
             */
            open_time: string;
            /**
             * Close Time
             * @default 23:00
             */
            close_time: string;
            /**
             * Rating
             * @default 4
             */
            rating: number;
        };
        /** ScheduleValidationResult */
        ScheduleValidationResult: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors?: components["schemas"]["ValidationIssue"][];
            /** Warnings */
            warnings?: components["schemas"]["ValidationIssue"][];
        };
        /** TransportConnectionResponse */
        TransportConnectionResponse: {
            /** Id */
            id: string;
            /** Origin Id */
            origin_id: string;
            /** Destination Id */
            destination_id: string;
            /** Mode */
            mode: string;
            /** Carrier */
            carrier?: string | null;
            /** Code */
            code?: string | null;
            /** Estimated Cost */
            estimated_cost: number;
            /** Typical Duration Minutes */
            typical_duration_minutes: number;
            /** Frequency */
            frequency?: string | null;
        };
        /** TransportLegDetail */
        TransportLegDetail: {
            /** Id */
            id: string;
            /** Trip Id */
            trip_id: string;
            /** Origin Stop Id */
            origin_stop_id: string;
            /** Destination Stop Id */
            destination_stop_id: string;
            /** Mode */
            mode: string;
            /** Carrier */
            carrier?: string | null;
            /** Departure Time */
            departure_time: string;
            /** Arrival Time */
            arrival_time: string;
            /** Cost */
            cost: number;
            /** Status */
            status: string;
        };
        /** TriggerDisruptionRequest */
        TriggerDisruptionRequest: {
            /** Trip Id */
            trip_id: string;
            type: components["schemas"]["CoreDisruptionType"];
            /** Affected Item Id */
            affected_item_id?: string | null;
            /** Affected Leg Id */
            affected_leg_id?: string | null;
            /** Affected Place Id */
            affected_place_id?: string | null;
            /** Effective Date */
            effective_date?: string | null;
            /** Effective Time */
            effective_time?: string | null;
            /** Delay Minutes */
            delay_minutes?: number | null;
            /** Reason */
            reason?: string | null;
            /** Reduction Amount */
            reduction_amount?: number | null;
            /** Replacement Budget */
            replacement_budget?: number | null;
            /** Weather Categories */
            weather_categories?: string[];
        };
        /** TriggerDisruptionResponse */
        TriggerDisruptionResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Trip Id */
            trip_id: string;
            disruption_analysis: components["schemas"]["DisruptionAnalysisResult"];
            proposed_replan: components["schemas"]["ProposedReplan"];
            diff: components["schemas"]["PlanDiffResult"];
            /** Replan Id */
            replan_id: string;
        };
        /** TriggerSimulationRequest */
        TriggerSimulationRequest: {
            /** Trip Id */
            trip_id: string;
            type: components["schemas"]["WhatIfType"];
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** TriggerSimulationResponse */
        TriggerSimulationResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Simulation Id */
            simulation_id: string;
            /** Trip Id */
            trip_id: string;
            type: components["schemas"]["WhatIfType"];
            /** Feasible */
            feasible: boolean;
            /** Current Summary */
            current_summary: {
                [key: string]: unknown;
            };
            /** Proposed Summary */
            proposed_summary: {
                [key: string]: unknown;
            };
            diff: components["schemas"]["PlanDiffResult"];
            budget_before: components["schemas"]["BudgetCalculationResult"];
            budget_after: components["schemas"]["BudgetCalculationResult"];
            validation_before: components["schemas"]["ScheduleValidationResult"];
            validation_after: components["schemas"]["ScheduleValidationResult"];
            /** Warnings */
            warnings?: string[];
            /** Errors */
            errors?: string[];
        };
        /** TripDetailResponse */
        TripDetailResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Total Budget */
            total_budget: number;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Status */
            status: string;
            /** Traveler Count */
            traveler_count: number;
            /** Duration Days */
            duration_days: number;
            /** Interests */
            interests: string[];
            /** Stops */
            stops: components["schemas"]["TripStopDetail"][];
            /** Transport Legs */
            transport_legs: components["schemas"]["TransportLegDetail"][];
            /** Itinerary */
            itinerary: components["schemas"]["ItineraryItemDetail"][];
            budget: components["schemas"]["BudgetCalculationResult"];
            validation: components["schemas"]["ScheduleValidationResult"];
            /** Version Hash */
            version_hash: string;
        };
        /** TripPlanRequest */
        TripPlanRequest: {
            /**
             * Destinations
             * @description List of city/destination names.
             */
            destinations: string[];
            /**
             * Duration Days
             * @description Total days for the trip.
             */
            duration_days: number;
            /**
             * Budget
             * @description Total budget in INR.
             */
            budget: number;
            /** Start Date */
            start_date?: string | null;
            /**
             * Travelers
             * @description Number of travelers.
             * @default 1
             */
            travelers: number;
            /** Interests */
            interests?: string[];
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** Starting Point */
            starting_point?: string | null;
            /** Constraints */
            constraints?: string | null;
        };
        /** TripStopDetail */
        TripStopDetail: {
            /** Id */
            id: string;
            /** Trip Id */
            trip_id: string;
            /** Destination Id */
            destination_id: string;
            /** Destination Name */
            destination_name: string;
            /** Order Index */
            order_index: number;
            /** Arrival Date */
            arrival_date: string;
            /** Departure Date */
            departure_date: string;
            /** Stop Budget */
            stop_budget: number;
            /** Hotel */
            hotel?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            type: components["schemas"]["ValidationIssueType"];
            severity: components["schemas"]["ValidationSeverity"];
            /** Message */
            message: string;
            /** Item Id */
            item_id?: string | null;
            /** Conflicting Item Id */
            conflicting_item_id?: string | null;
            /** Day Number */
            day_number?: number | null;
            /** Suggested Fix */
            suggested_fix?: string | null;
        };
        /**
         * ValidationIssueType
         * @enum {string}
         */
        ValidationIssueType: "invalid_time_range" | "overlap" | "travel_conflict" | "venue_closed_hours" | "venue_closed_day" | "date_out_of_bounds" | "stop_boundary_violation" | "transport_conflict" | "insufficient_buffer";
        /**
         * ValidationSeverity
         * @enum {string}
         */
        ValidationSeverity: "error" | "warning";
        /**
         * WhatIfType
         * @enum {string}
         */
        WhatIfType: "BUDGET_CHANGE" | "ADD_DAY" | "REMOVE_DESTINATION" | "REPLACE_DESTINATION" | "ADD_ACTIVITY";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_destinations_api_destinations_get: {
        parameters: {
            query?: {
                /** @description Search term for destination name or state */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destination_api_destinations__destination_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                destination_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_trip_api_trips_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_agent_api_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_events_api_agent_events__trip_id__get: {
        parameters: {
            query?: {
                /** @description Max number of events to retrieve (1-100) */
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_disruption_api_disruptions_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerDisruptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerDisruptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_replan_api_disruptions__replan_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyReplanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_replan_api_disruptions__replan_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectReplanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_what_if_simulation_api_simulations_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerSimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerSimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_simulation_api_simulations__simulation_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplySimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_simulation_api_simulations__simulation_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectSimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
